internship/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from login.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('login.urls')),
    url(r'^', include('launcher.urls')),
    url(r'^', include('interview.urls')),
]

interview/urls.py
from django.conf.urls import url

from . import views

app_name = 'interview'
urlpatterns = [
    url(
        regex=r'^calendar/$',
        view=views.calendar,
        name='calendar'
    ),
    # url(
    #     regex=r'^calendar/export/$',
    #     view=views.export_date,
    #     name='export_date'
    # ),
    # url(
    #     regex=r'^calendar/auth/callback/$',
    #     view=views.auth_callback,
    #     name='auth_callback'
    # ),
    url(
        regex=r'^calendar/send_email/$',
        view=views.send_email,
        name='send_email'
    ),
    url(
        regex=r'^calendar/save_events_to_appointment_slots/$',
        view=views.save_events_to_appointment_slots,
        name='save_events_to_appointment_slots'
    ),
    url(
        regex=r'^calendar/get_appointment_slots/$',
        view=views.get_appointment_slots,
        name='get_appointment_slots'
    ),
    url(
        regex=r'^calendar/get_teacher_free_slots/$',
        view=views.get_teacher_free_slots,
        name='get_teacher_free_slots'
    ),
    url(
        regex=r'^calendar/get_student_info/$',
        view=views.get_student_info,
        name='get_student_info'
    ),
    url(
        regex=r'^calendar/delete_appointment_slot/$',
        view=views.delete_appointment_slot,
        name='delete_appointment_slot'
    ),
    url(
        regex=r'^calendar/change_event_to_reserve_slots/$',
        view=views.change_event_to_reserve_slots,
        name='change_event_to_reserve_slots'
    ),
    url(
        regex=r'^calendar/selected/(?P<id>[0-9]+)$',
        view=views.selection_slot,
        name='selection_slot'
    ),
    url(
        regex=r'^calendar/translate_calendar/$',
        view=views.translate_calendar,
        name='translate_calendar'
    ),
    url(
        regex=r'^calendar/scheduler_student_base/$',
        view=views.scheduler_student_base,
        name='scheduler_student_base'
    ),
    url(
        regex=r'^calendar/selected/$',
        view=views.scheduler_student,
        name='scheduler_student'
    ),
    url(
        regex=r'^calendar/get_reserve_slot/$',
        view=views.get_reserve_slot,
        name='get_reserve_slot'
    ),
]

launcher/urls.py
from django.conf.urls import url

from . import views

app_name = 'scheduler'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^project/$', views.project, name='project'),
    url(r'^student/$', views.student, name='student'),
    url(r'^teacher/$', views.teacher, name='teacher'),
    url(r'^change_status_application/$', views.change_status_application, name='change_status_application'),
]

login/urls.py
from django.conf.urls import url
from . import views

app_name = 'login'
urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^home/$', views.home, name='home'),
    url(r'^register/$', views.register, name='register'),
    url(r'^register/success/$', views.register_success, name='register_success'),
    url(r'^logout/$', views.logout_page, name='logout'),
]

templates/base.html
<!-- base.html -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{% load staticfiles %}
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    {% load render_bundle from webpack_loader %}
    {% render_bundle 'css' %}
    <script type="text/javascript" src="https://rawgithub.com/nwcell/ics.js/master/ics.deps.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            {% if user.first_name %}
                <a class="navbar-brand" href="{% url 'scheduler:index' %}">{{ user.first_name }} {{ user.last_name }}</a>
            {% else %}
                <a class="navbar-brand" href="{% url 'scheduler:index' %}">{{ user.username }}</a>
            {% endif %}
        </div>
        <div class="navbar-collapse collapse">
            {% if user.is_authenticated %}
                <form class="navbar-form navbar-right" >
                    <a class="btn btn-default pull-right" href="{% url 'login:logout' %}">Log out</a>
                </form>
            {% else %}
                <form class="navbar-form navbar-right" method="post" action="{% url 'login:login' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" placeholder="Username" name="username" class="form-control">
                    </div>
                    <div class="form-group">
                        <input type="password" placeholder="Password" name="password" class="form-control">
                    </div>
                    <button type="submit" class="btn btn-success">Sign in</button>
                    <a class="btn btn-info" href="{% url 'login:register' %}">Register</a>
                </form>
            {% endif %}
        </div>
    </div>
</div>
{% block head %}{% endblock %}
{% block content %}{% endblock %}

{#<div id="react-app"></div>#}
{#{% render_bundle 'main' %}#}
</body>
</html>

templates/home.html
<!-- home.html -->

{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Welcome to Django{% endblock %}
{% block head %}
    <div class="jumbotron">
        <div class="container">
            {% if not user.is_authenticated %}
                <h1>Hello! Welcome to internship applications</h1>
                <p>Please Sign in on this website</p>
            {% else %}
                {% if user.first_name %}
                    <h1>{{ user.first_name }} {{ user.last_name }}</h1>
                {% else %}
                    <h1>{{ user.username }}</h1>
                {% endif %}
                <p> Добро пожаловать</p>
                {% if not user.is_staff %}
                    <a class="btn btn-default" href="{% url 'scheduler:student' %}">Проект и информация</a>
                    <a class="btn btn-default" href="{% url 'interview:scheduler_student' %}">Мое расписание</a>
                {% else %}
                    <h4>{{ user.username }} лучший учитель насвете</h4>
                    <a class="btn btn-info" href="{% url 'scheduler:project' %}">Добавить проект</a>
                    <a class="btn btn-default" href="{% url 'interview:calendar' %}">Твой кадендарь</a>
                    <a class="btn btn-success" href="{% url 'scheduler:teacher' %}">Студенты</a>
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h2>Heading</h2>
                <p>Ту просто какой-то текст. Можно использовать что хочешь</p>
                <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div>
        </div>
    </div>
{% endblock %}

templates/temp.html
{% extends "base.html" %}
{% block content %}
    <h1> Welcome {{ user.username }} !!! </h1>
{% endblock %}