internship/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from login.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('login.urls')),
    url(r'^', include('launcher.urls')),
    url(r'^', include('interview.urls')),
]

interview/urls.py
from django.conf.urls import url

from . import views

app_name = 'interview'
urlpatterns = [
    url(
        regex=r'^calendar/$',
        view=views.calendar,
        name='calendar'
    ),
    # url(
    #     regex=r'^calendar/export/$',
    #     view=views.export_date,
    #     name='export_date'
    # ),
    # url(
    #     regex=r'^calendar/auth/callback/$',
    #     view=views.auth_callback,
    #     name='auth_callback'
    # ),
    url(
        regex=r'^calendar/send_email/$',
        view=views.send_email,
        name='send_email'
    ),
    url(
        regex=r'^calendar/save_events_to_appointment_slots/$',
        view=views.save_events_to_appointment_slots,
        name='save_events_to_appointment_slots'
    ),
    url(
        regex=r'^calendar/get_appointment_slots/$',
        view=views.get_appointment_slots,
        name='get_appointment_slots'
    ),
    url(
        regex=r'^calendar/get_teacher_free_slots/$',
        view=views.get_teacher_free_slots,
        name='get_teacher_free_slots'
    ),
    url(
        regex=r'^calendar/get_student_info/$',
        view=views.get_student_info,
        name='get_student_info'
    ),
    url(
        regex=r'^calendar/delete_appointment_slot/$',
        view=views.delete_appointment_slot,
        name='delete_appointment_slot'
    ),
    url(
        regex=r'^calendar/change_event_to_reserve_slots/$',
        view=views.change_event_to_reserve_slots,
        name='change_event_to_reserve_slots'
    ),
    url(
        regex=r'^calendar/selected/(?P<id>[0-9]+)$',
        view=views.selection_slot,
        name='selection_slot'
    ),
    url(
        regex=r'^calendar/translate_calendar/$',
        view=views.translate_calendar,
        name='translate_calendar'
    ),
    url(
        regex=r'^calendar/scheduler_student_base/$',
        view=views.scheduler_student_base,
        name='scheduler_student_base'
    ),
    url(
        regex=r'^calendar/selected/$',
        view=views.scheduler_student,
        name='scheduler_student'
    ),
    url(
        regex=r'^calendar/get_reserve_slot/$',
        view=views.get_reserve_slot,
        name='get_reserve_slot'
    ),
]

launcher/urls.py
from django.conf.urls import url

from . import views

app_name = 'scheduler'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^project/$', views.project, name='project'),
    url(r'^student/$', views.student, name='student'),
    url(r'^teacher/$', views.teacher, name='teacher'),
    url(r'^change_status_application/$', views.change_status_application, name='change_status_application'),
]

login/urls.py
from django.conf.urls import url
from . import views

app_name = 'login'
urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^home/$', views.home, name='home'),
    url(r'^register/$', views.register, name='register'),
    url(r'^register/success/$', views.register_success, name='register_success'),
    url(r'^logout/$', views.logout_page, name='logout'),
]

launcher/models.py
from django.contrib.auth.models import User
from django.db import models
from django_enumfield import enum


class Project(models.Model):
    title = models.CharField(max_length=127)
    description = models.CharField(max_length=127)
    mentor = models.ForeignKey(User)
    state = models.CharField(max_length=31)

    def __str__(self):
        return self.title


class AppointmentSlot(models.Model):
    user = models.ForeignKey(User, related_name='appointment_slots')
    student = models.ForeignKey(User, related_name='interviews', null=True, blank=True)

    start = models.DateTimeField()
    end = models.DateTimeField()
    is_synchronize = models.BooleanField()

    def __str__(self):
        return self.user.username


class StudentApplication(models.Model):
    student = models.ForeignKey(User, related_name='intern_students_id')
    project = models.ForeignKey(Project)
    is_approve = models.BooleanField(default=False)
    meeting = models.ForeignKey(AppointmentSlot, null=True, blank=True)


class FreeMeetingTime(models.Model):
    teacher = models.ForeignKey(User)
    from_date = models.DateTimeField()
    to_date = models.DateTimeField()


class ProjectStatusEnum(enum.Enum):
    REJECTED = 'REJ'
    APPROVED = 'APR'
    INVITED = 'INV'
    SUBMITTED = 'SUB'
    RECOMMENDED = 'REC'

    labels = {
        REJECTED: 'Rejected',
        APPROVED: 'Invited for the practice',
        INVITED: 'Invited for the interview',
        SUBMITTED: 'Submitted',
        RECOMMENDED: 'Recommended',
    }

class ProjectApplication(models.Model):
    class Meta:
        verbose_name = 'Project application'
        verbose_name_plural = 'Project applications'

    candidate = models.ForeignKey(User)
    project = models.ForeignKey(Project, related_name='internship')
    status = models.CharField('Status',
                              max_length=3,
                              choices=ProjectStatusEnum.choices(),
                              default=ProjectStatusEnum.SUBMITTED)

    def __str__(self):
        return self.candidate.username + ' ' \
               + self.project.mentor.username + ' ' \
               + self.project.title[:10]

launcher/forms.py
from django import forms

from launcher.models import Project


class ProjectForm(forms.Form):
    project = forms.ModelChoiceField(queryset=Project.objects.all())


class CreateProjectForm(forms.Form):
    title = forms.CharField(max_length=127)
    description = forms.CharField(max_length=127)

launcher/views.py
import json

from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render_to_response

from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt

from launcher.forms import ProjectForm, CreateProjectForm
from launcher.models import StudentApplication, FreeMeetingTime, Project

def index(request):
    return render_to_response(
        'home.html',
        {'user': request.user}
    )

@login_required(login_url='/')
def project(request):
    form = CreateProjectForm()
    mentor = auth.get_user(request)
    massage = ''
    if request.POST:
        form = CreateProjectForm(request.POST)
        if form.is_valid():
            ctx = form.cleaned_data
            Project.objects.create(
                mentor=mentor,
                title=ctx['title'],
                description=ctx['description'],
                state=0
            )
            massage = "Новый проект добавлен!!!"
    return render(request, 'launcher/project.html', {
        'form': form,
        'massage': massage,
    })


@login_required(login_url='/')
def student(request):
    form = ProjectForm()
    student = auth.get_user(request)
    if request.POST:
        form = ProjectForm(request.POST)
        if form.is_valid():
            ctx = form.cleaned_data
            StudentApplication.objects.get_or_create(
                student=student,
                project=ctx['project'],
            )

    applications = StudentApplication.objects.filter(student=student)

    return render(request, 'launcher/student.html', {
        'form': form,
        'applications': applications,
    })


@login_required(login_url='/')
def teacher(request):
    mentor = auth.get_user(request)
    applications = StudentApplication.objects.filter(project__mentor=mentor)

    return render(request, 'launcher/teacher.html', {
        'applications': applications,
    })


@csrf_exempt
def change_status_application(request):
    application_id = request.POST['application_id']
    application = StudentApplication.objects.get(id=application_id)
    if application.is_approve:
        return JsonResponse({'success': False})
    application.is_approve = True
    application.save()
    return JsonResponse({'success': True})

#
# @login_required(login_url='/auth/login/')
# def calendar(request):
#     teacher = auth.get_user(request)
#
#     get_object_or_404(Person, pk=teacher.id, profession=settings.TEACHER)
#
#     student_time_data = StudentApplication.objects \
#         .filter(teacher_id=teacher.id) \
#         .filter(is_approve=True) \
#         .exclude(meeting=None)
#
#     student_time = []
#     for item in student_time_data:
#         date = item.meeting + timedelta(hours=3)
#         person = Person.objects.filter(profession=settings.STUDENT).filter(pk=item.student_id).values().first()
#         student_time.append({
#             'from_date': date.isoformat(timespec='seconds'),
#             'to_date': (date + timedelta(minutes=30)).isoformat(timespec='seconds'),
#             'name': person['first_name'] + ' ' + person['last_name'],
#         })
#
#     meetings_time = []
#     for item in FreeMeetingTime.objects.filter(teacher_id=teacher.id):
#         meetings_time.append({
#             'from_date': (item.from_date + timedelta(hours=3)).isoformat(timespec='seconds'),
#             'to_date': (item.to_date + timedelta(hours=3)).isoformat(timespec='seconds'),
#             'id': item.id,
#         })
#
#     context = {
#         'calendar_id': teacher.id,
#         'meetings_time': meetings_time,
#         'student_time': student_time,
#         'username': teacher.first_name,
#     }
#
#     return render(request, 'launcher/calendar.html', context)
#
#
# @csrf_exempt
# @login_required
# def update_status(request):
#     teacher_id = request.POST['teacher_id']
#     student_id = request.POST['student_id']
#
#     student = get_object_or_404(StudentApplication, student_id=student_id, teacher_id=teacher_id)
#
#     if student:
#         student.is_approve = True
#         student.save()
#         return JsonResponse({'success': True})
#     else:
#         return JsonResponse({'success': False})
#

templates/launcher/project.html
{% extends 'base.html' %}
{% block head %}
    <br/>
    <br/>

    <h1>Добавим проект</h1><br>
    <form method="post" action="{% url 'scheduler:project' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Sign in</button>
    </form>
    {{ massage }}
{% endblock %}

templates/launcher/student.html
{% extends 'base.html' %}
{% block head %}
    <br/>
    <br/>
    <br/>
    <form class="form-inline" action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form }}
            {#            <select id="company" class="form-control">#}
            {#                {% for project in projects %}#}
            {#                    <option value={{ project.id }}>{{ project.title }} => {{ project.description }}</option>#}
            {#                {% endfor %}#}
            {#            </select>#}
        </div>
        <button type="submit" class="btn btn-success">submit</button>
    </form>

    <h1>Список ваших заявок:</h1><br>
    <table class="table" >
        <thead>
        <tr>
            <th>Mentor</th>
            <th>Decription</th>
            <th>Choose Time</th>
        </tr>
        </thead>
        <tbody>
        {% for application in applications %}
            <tr>
                <td>{{ application.project.mentor }}</td>
                <td>{{ application.project.description }}</td>
                {% if application.is_approve %}
                    <td>
                        <a href="{% url 'interview:selection_slot' application.project.mentor.id %}" class="btn btn-success">Выбрать время</a>
{#                        <button type="button" value="{{ application.id }}" class="btn btn-success">Выбрать время</button>#}
                    </td>
                {% else %}
                    <td>
                        <button type="button" class="btn btn-danger" disabled="disabled">Выбрать время</button>
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <script>
      {#$('.btn').on('click', function (data) {#}
      {#    ($(this).val());})#}
    </script>
{% endblock %}

templates/launcher/teacher.html
{% extends 'base.html' %}
{% block head %}
    <br/>
    <br/>

    <h1>Список заявок к вам:</h1><br>
    <table class="table">
        <thead>
        <tr>
            <th>Student</th>
            <th>Project</th>
            <th>Approve</th>
        </tr>
        </thead>
        <tbody>
        {% for application in applications %}
            <tr>
                <td>{{ application.student }}</td>
                <td>{{ application.project}}</td>
                <td>
                    <button id='id_approve_button' type="button" value="{{ application.id }}" class="btn btn-success">Дать дабро</button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <script>
    $("td button").click( function(){
        application_id = $(this).val();
        url = '{%  url 'scheduler:change_status_application' %}';
        $.ajax({
            'url' : url,
            'type' : 'POST',
            'data' : {
                'application_id' : application_id,
            },
            'success' : function(data) {
                            if (data.success) {
                                alert('Success!');
                            } else {
                                alert('Feild already exists!!!');
                            }
                        }
        });
    });

</script>
{% endblock %}